name: ogc_workshop
channels:
  - conda-forge
dependencies:
  - python = 3.12
  - cartopy
  - geopandas
  - rasterio
  - xarray
  - rioxarray
  - owslib
  - numpy
  - matplotlib
  - pandas
  - descartes
  - folium
  - ipyleaflet
